language: perl
perl:
  - "5.22"
  
install:
  - cpanm Encode
  - cpanm Encode::Detect
  - cpanm Test::More

notifications:
  email:
    recipients:
      - stalk.calvin@gmail.com
    on_success: change
    on_failure: always

script: perl Makefile.PL && make test

