language: perl
perl:
  - "5.22"
  
install:
  - cpanm Test::More
  - cpanm XML::Dumper
  - cpanm MIME::Base64
  - cpanm JSON

notifications:
  email:
    recipients:
      - stalk.calvin@gmail.com
    on_success: change
    on_failure: always

script: perl Makefile.PL && make test

