language: perl
perl:
  - "5.22"

before_install:
  - sudo apt-get update
  - sudo apt-get install host
  
install:
  - cpanm Test::More@1.302067
  - cpanm XML::Dumper@0.81
  - cpanm MIME::Base64@3.15
  - cpanm JSON@2.90
  - cpanm Log::Log4perl@1.49

notifications:
  email:
    recipients:
      - stalk.calvin@gmail.com
    on_success: change
    on_failure: always

script: perl Makefile.PL && make test

